import ComplexityTheory.Foundations.BinaryString
import ComplexityTheory.Foundations.NatEncoding
import ComplexityTheory.Foundations.BooleanFormula
import ComplexityTheory.Foundations.FormulaEncoding
import ComplexityTheory.Foundations.FormulaRestriction
import ComplexityTheory.Foundations.FormulaPadding
import ComplexityTheory.ProofComplexity.ProofSystem
import ComplexityTheory.ProofComplexity.Verifier
import ComplexityTheory.ProofComplexity.LowerBound
import ComplexityTheory.ProofComplexity.Simulation

/-!
# ComplexityTheory

A formalization of computational complexity theory.
-/
